### ISSUE TITLE
Ошибка gulp

### ISSUE THREAD

**Issue by kissarat** [artemsky/EvartSocial#1]
<img width="394" alt="screen shot 2016-09-06 at 5 28 27 am" src="https://cloud.githubusercontent.com/assets/1538346/18260022/d71da4b8-73f2-11e6-8c67-653c3afd7647.png">
Поэтому регистрация выглядит так dist/registration.html
<img width="1219" alt="screen shot 2016-09-06 at 6 27 18 am" src="https://cloud.githubusercontent.com/assets/1538346/18260948/5c8a1976-73fb-11e6-866c-e46154d02bbc.png">
Хотя dist/messenger.html выглядит нормально

**Comment by artemsky** [comment]
Я не уверен, но кадется, по какой-то причине у тебя gulp не 4ой версии.
![image](https://cloud.githubusercontent.com/assets/16777197/18264033/7bbc85b6-7416-11e6-9fb2-fc892b867c5d.png)
проверь, и если нет -то
`npm rm gulp-cli -g`
`npm install gulpjs/gulp-cli -g`
` npm install gulpjs/gulp#4.0 --save-dev`

**Comment by kissarat** [comment]
gulp prod выполнился, но всеравно /css/registration.css Not Found. У меня document root настроен на папку dist и не вижу, чтобы папка css где-то существовала

**Comment by artemsky** [comment]
fixed path -> `css` replaced with `libs`
